### ISSUE TITLE
Follows Adjacent Logs Infinitely

### ISSUE THREAD

**Issue by Xavyrr** [Levoment/SuperAxes#6]
Hello,

It appears that the super axe will rip down adjacent trees infinitely without limit until the axe breaks or the game/server crashes (think creative mode without durability, or higher end axes) - so for custom terrain generation and biomes that have closely knit trees, such as a mangrove biome from Oh The Biomes You'll Go, this causes issues. I would guess config settings to limit the x/y travel from the original block broken (default to maybe 8 or 16 blocks, most trees wouldn't be that large, and an unlimted y axis would still allow for super tall trees) would fix this. Maybe.

Here's a GIF with an iron superaxe (diamond and netherine takes way too long for a gif):
![superaxebug_short](https://user-images.githubusercontent.com/10913345/88446598-6a2b6100-cdf9-11ea-88af-d7d7e037d0d3.gif)

Thank you for the work you do on this mod.

**Comment by Levoment** [comment]
I have made a configuration option to limit the radius to scan for logs. By default it is set to not limit the search, but by going into the configuration screen one can set it up. If **Yes** is selected it will by default limit the search radius to 8. The radius can be modified.

I need to test more to decide whether or not to make it **Yes** by default because to my knowledge that seems to be the only on biomes that purposefully connect tree logs. For example, the same happens on the Japanese Maple Biome and Sakura biome in Terrestria. The reason it happens is because those biomes create trees whose logs are connected by other logs. Those biomes, instead of making trees like this https://commons.wikimedia.org/wiki/File:Sequoiafarm_Sequoiadendron_giganteum.jpg and connect them by leaves close to each other (how Vanilla trees usually do), they make trees like this https://commons.wikimedia.org/wiki/File:Bombax_LalBagh.JPG and connect them by their logs such there is a chance that every XZ position in a chunk of those biomes has a log in it. Some Sakura trees in Terrestria for example are connected like this https://en.wikipedia.org/wiki/Inosculation

I'll be committing the changes soon.

**Comment by Levoment** [comment]
I have added the changes. If one opens now the configuration screen, there is an option to limit the radius to search for logs to harvest. I need to test it more before making it available on CF, but if someone would like to try it right now, they can always download the GitHub release here: https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F1.1.5

**Comment by Xavyrr** [comment]
So I have been using this for a while, it seems to work mostly as intended, but the behavior is a little odd for tree's that touch each other. I've also found another bug I believe so I will open another and mark this one closed for now since I think the issue here is addressed. Thank you!
