### ISSUE TITLE
Sometimes, using a SuperAxe causes a crash

### ISSUE THREAD

**Issue by davidthehat** [Levoment/SuperAxes#7]
https://pastebin.com/3MH5RW2E

I'm using AOF3 modpack.

**Comment by Levoment** [comment]
Thanks for the report.

I have created an issue on AOF3 recommending my mod to be removed from the modpack. Because I have a low end computer I can't try AOF3 to reproduce the problem. Although reproducing the problem would not help much because the stacktrace is a generic error that doesn't trace back to the method of SuperAxes that was called before the crash.

I recommend that in the meantime, while the mod is removed from the pack to not use the SuperAxes mod. **Trees Do Not Float** is a mod I believe is included in the pack which can be used to harvest wood quickly.
